CREATE TABLE blood_bank (
    bank_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR(100),
    location VARCHAR(100)
);

CREATE TABLE donor (
    donor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    blood_group VARCHAR(5),
    phone VARCHAR(15)
);

CREATE TABLE recipient (
    recipient_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    blood_group VARCHAR(5),
    phone VARCHAR(15)
);

CREATE TABLE donation (
    donation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id INT REFERENCES donor(donor_id),
    bank_id INT REFERENCES blood_bank(bank_id),
    donation_date DATE,
    quantity_ml INT
);

CREATE TABLE request (
    request_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INT REFERENCES recipient(recipient_id),
    bank_id INT REFERENCES blood_bank(bank_id),
    request_date DATE,
    quantity_ml INT
);

INSERT INTO blood_bank (bank_name, location)
VALUES ('City Blood Bank', 'Chennai');

INSERT INTO donor (name, age, blood_group, phone)
VALUES ('Arun', 22, 'A+', '9876543210');

INSERT INTO recipient (name, age, blood_group, phone)
VALUES ('Rahul', 25, 'A+', '9123456780');

INSERT INTO donation (donor_id, bank_id, donation_date, quantity_ml)
VALUES (1, 1, '2026-02-20', 450);

INSERT INTO request (recipient_id, bank_id, request_date, quantity_ml)
VALUES (1, 1, '2026-02-20', 300);
SELECT * FROM donor;
SELECT d.name, b.bank_name
FROM donor d
JOIN donation dn ON d.donor_id = dn.donor_id
JOIN blood_bank b ON b.bank_id = dn.bank_id;
